AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
    - spec/**/*
    - app/extensions/*
    - app/routes/*
    - lib/tasks/*
    - app.rb

Documentation:
  Enabled: false
ModuleFunction:
  Enabled: false
MethodDefParentheses:
  Enabled: false
EmptyLiteral:
  Enabled: false
