-
  :ship_type: :aircraft_carrier
  :direction: :vertical
  :position:
    :x: 0
    :y: 1
-
  :ship_type: :battleship
  :direction: :vertical
  :position:
    :x: 0
    :y: 2
-
  :ship_type: :submarine
  :direction: :horizontal
  :position:
    :x: 6
    :y: 1
-
  :ship_type: :destroyer
  :direction: :vertical
  :position:
    :x: 7
    :y: 0
-
  :ship_type: :patrol_boat
  :direction: :horizontal
  :position:
    :x: 0
    :y: 8
-
  :ship_type: :patrol_boat
  :direction: :vertical
  :position:
    :x: 1
    :y: 8
